# Generated by Django 5.2.17 on 2026-09-30 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_translationlog_translationcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('analysis_generated', 'Analysis Generated'), ('analysis_failed', 'Analysis Failed'), ('rewrite_generated', 'Rewrite Generated'), ('rewrite_decision', 'Rewrite Decision'), ('override', 'Override'), ('insight_generated', 'Insight Generated'), ('mark_reviewed', 'Marked Reviewed')], db_index=True, max_length=40)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PSInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_summary', models.TextField(blank=True, default='')),
                ('top_issues', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('run_id', models.CharField(blank=True, default='', max_length=36)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='core.challenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewriteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('professional', 'Professional'), ('concise', 'Concise'), ('formal', 'Formal'), ('simple', 'Easy to Understand'), ('structured', 'Structured')], max_length=20)),
                ('original_text', models.TextField()),
                ('ai_text', models.TextField()),
                ('validation_warnings', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('edited', 'Edited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('final_text', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_suggestions', to='core.application')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewrite_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cleaned_response', models.TextField(blank=True, default='')),
                ('short_summary', models.TextField(blank=True, default='')),
                ('key_points', models.JSONField(default=list)),
                ('main_issue', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('category_confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(blank=True, choices=[('normal', 'Normal'), ('concerning', 'Concerning'), ('critical', 'Critical')], default='', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='', max_length=20)),
                ('priority_score', models.IntegerField(db_index=True, default=0)),
                ('priority_reason', models.TextField(blank=True, default='')),
                ('flags', models.JSONField(default=list)),
                ('flag_details', models.JSONField(default=dict)),
                ('input_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='core.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('category', 'Category'), ('priority', 'Priority'), ('severity', 'Severity'), ('flags', 'Flags')], max_length=20)),
                ('ai_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='ai_assist.submissionanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.IntegerField(default=0)),
                ('avg_priority_score', models.FloatField(default=0.0)),
                ('run_id', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.challenge')),
                ('member_analyses', models.ManyToManyField(blank=True, related_name='cluster_memberships', to='ai_assist.submissionanalysis')),
                ('representative_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_of', to='ai_assist.submissionanalysis')),
            ],
        ),
        migrations.AddIndex(
            model_name='submissionanalysis',
            index=models.Index(fields=['application', 'is_current'], name='ai_assist_s_applica_cfd6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionanalysis',
            index=models.Index(fields=['priority_score'], name='ai_assist_s_priorit_66eeda_idx'),
        ),
    ]
