# Generated by Django 5.2.17 on 2026-09-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scaleupentry_adopted_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam')], default='en', max_length=10),
        ),
    ]
