# Generated by Django 5.2.17 on 2026-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_text', models.TextField()),
                ('source_lang', models.CharField(max_length=8)),
                ('target_lang', models.CharField(max_length=8)),
                ('provider', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text_hash', models.CharField(db_index=True, max_length=64)),
                ('source_lang', models.CharField(default='en', max_length=8)),
                ('target_lang', models.CharField(max_length=8)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text_hash', 'target_lang'], name='core_transl_source__f65c6d_idx')],
                'unique_together': {('source_text_hash', 'target_lang')},
            },
        ),
    ]
